mywatson_site/mywatson/urls.py
from django.urls import path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.views.static import serve

from . import views



handler404 = 'mywatson.views.handler404'
handler500 = 'mywatson.views.handler500'
app_name = 'mywatson'
urlpatterns = [
    path('', login_required(views.GalleryView.as_view()), name='index'),
    path('upload/', login_required(views.upload_photo), name='upload_photo'),
    path('<int:pk>/', login_required(views.DetailView.as_view()), name='photo'),
    path('results', login_required(views.QueryResultsView.as_view()), name='query'),
    path('<int:pk>/add-tag', login_required(views.AddTagView.as_view()), name='add_tag'),
    # path('people', login_required(views.ClusterView.as_view()), name='people'),
    path('people', login_required(views.ClusterView.as_view()), name='people'),
    path('get_people', login_required(views.get_people), name='get_people'),
	url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mywatson_site/mywatson_site/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from core import views as core_views
from django.conf.urls.static import static
from django.conf import settings

from core.forms import CustomAuthForm

from django.views.generic.base import RedirectView

from django.views.static import serve



urlpatterns = [
    # path('', core_views.index, name='index'),
    path('', core_views.landing, name='landing'),

    path('login', auth_views.login,
          {'template_name': 'core/login.html',
           'authentication_form': CustomAuthForm,
		   'redirect_authenticated_user': True}, name='login'),

    path('mywatson/', include('mywatson.urls'), name='mywatson'),
    path('admin/', admin.site.urls),
    url(r'^signup/$', core_views.signup, name='signup'),
    # url(r'^login/$', auth_views.login, {'template_name': 'core/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),

    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

    # url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', core_views.activate, name='activate'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mywatson_site/mywatson/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField
import os
import json

####################################################################


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/photos/user_<id>/<filename>
    path = 'photos/{0}/{1}'.format(instance.user, filename)
    return path


FACES_FOLDER = 'faces'


class Photo(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to=user_directory_path)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)


class Tag(models.Model):
    tag = models.CharField(max_length=100, default="tag")
    category = models.CharField(max_length=20, default="None")
    score = models.DecimalField(default=1, decimal_places=3, max_digits=6)
    photo = models.ForeignKey(Photo, null=True, on_delete=models.CASCADE)
    startX = models.IntegerField(null=True)
    startY = models.IntegerField(null=True)
    endX = models.IntegerField(null=True)
    endY = models.IntegerField(null=True)


class InvertedIndex(models.Model):
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    photo = models.ForeignKey(Photo, on_delete=models.CASCADE)


class Face(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    face = models.ImageField(max_length=256)
    photo = models.ForeignKey(Photo, null=True, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, null=True, on_delete=models.CASCADE)


class FaceCluster(models.Model):
    n_clusters = models.IntegerField(null=True)
    cluster_id = models.IntegerField(null=True)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    face = models.ForeignKey(Face, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, null=True)
    silhouette_score = models.FloatField(default=0)

    class Meta:
        unique_together = ('n_clusters', 'cluster_id', 'face')


class UserPreferences(models.Model):
    """
    Saves the user preferences like the number of clusters to display
    """
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    n_clusters = models.IntegerField(null=True)

    class Meta:
        unique_together = ('user', 'n_clusters')

class Features(models.Model):
    face = models.ForeignKey(Face, null=True, on_delete=models.CASCADE)
    feature = models.TextField()

    def set_feature(self, x):
        self.feature = json.dumps(x)

    # def get_feature(self):
    #     return json.loads(self.feature)

    # Although these two functions look the same,
    # the first one cannot return anything other than a string,
    # as it is an attribute getter
    def get_feature_list(self):
        return json.loads(self.feature)
####################################################################
# Signals
####################################################################


@receiver(models.signals.post_delete, sender=Photo)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes image from filesystem
    when corresponding 'Photo' object is deleted.
    """
    if instance.image:
        if os.path.isfile(instance.image.path):
            try:
                # os.remove(instance.image.path)
                with open('to_remove.txt', 'a', encoding='utf-8') as to_remove:
                    to_remove.write('\n')
                    to_remove.write(instance.image.path)
            except PermissionError as e:
                print("[ERROR] When deleting", instance.image.path)
                print(e)


@receiver(models.signals.pre_save, sender=Photo)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """
    Deletes old file from filesystem
    when corresponding 'Photo' object is updated
    with new file.
    """
    if not instance.pk:
        return False
    try:
        old_file = Photo.objects.get(pk=instance.pk).image
    except Photo.DoesNotExist:
        return False

    new_file = instance.image
    if not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)


@receiver(models.signals.post_delete, sender=Face)
def force_cluster_recompute_on_delete(sender, instance, **kwargs):
    """
    The removal of an image / tag triggers the deletion of the corresponding face / faces.
    Therefore when one of those faces are deleted, ALL the clusters should be recomputed.
    """
    if instance.face:
        FaceCluster.objects.all().delete()


@receiver(models.signals.post_delete, sender=FaceCluster)
def reset_user_preferences_on_cluster_delete(sender, instance, **kwargs):
    """
    The removal of any cluster should cause the user preferences to be reset.
    """
    if instance.user_id:
        UserPreferences.objects.all().delete()

mywatson_site/mywatson/forms.py
from django import forms
from .models import Photo


class ImageUploadForm(forms.ModelForm):

    class Meta:
        model = Photo
        exclude = ['user']

mywatson_site/mywatson/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseForbidden, JsonResponse
from django.urls import reverse
from django import forms
from django.http import Http404

from django.shortcuts import render_to_response
from django.template import RequestContext

from .models import Photo, Tag, InvertedIndex, Face, FaceCluster, UserPreferences
from .forms import ImageUploadForm

from .app_modules import MyWatsonApp, security
from mywatson_site.settings import BASE_DIR, MEDIA_ROOT
import os
from PIL import Image
from sorl.thumbnail import ImageField
from django.core.files.images import ImageFile
from .vars import *

import urllib.parse

import json
from django.core import serializers

import html

from django.template.defaulttags import register

import hashlib


###############################################################################

def handler404(request, exception, template_name='404.html'):
    response = render_to_response('404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 404
    return response


def handler500(request, exception, template_name='500.html'):
    response = render_to_response('500.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 500
    return response

###############################################################################


def sizeof_fmt(num, suffix='B'):
    for unit in ['', 'K', 'M', 'G', 'T', 'P', 'E', 'Z']:
        if abs(num) < 1024.0:
            return "%3.1f%s%s" % (num, unit, suffix)
        num /= 1024.0
    return "%.1f%s%s" % (num, 'Yi', suffix)


def get_user_id(request):
	return request.user.id


def new_face(photo, box, tag):
	image_path_tokens = photo.image.url.split("/")
	image_path_file = image_path_tokens[-1]
	ext = image_path_file.split(".")[-1]
	# face_file_name = image_path_file.split(".")[0] + "_face_0." + ext
	face_file_name = image_path_file.split(".")[0]
	user_name = photo.user.username
	face_folder = os.path.join(FACE_IMAGES_FOLDER, user_name)

	if not os.path.exists(face_folder):
		os.makedirs(face_folder)

	face = Face.objects.create(user=photo.user, tag=tag)
	id = face.id

	# django_face_file_path = user folder to save the face image: "faces/Watson"
	django_face_file_path = os.path.join("faces", user_name)

	# face_file_name: "pedro_1_face_99.jpg"
	face_file_name = face_file_name + "_face_" + str(id) + "." + ext

	# face_path = full path of the file
	face_path = os.path.join(FACE_IMAGES_FOLDER, user_name, face_file_name)

	crop(photo.image, box, face_path)

	# face.face = relative path to the media folder: "faces\Watson\pedro_face.jpg"

	face.face = os.path.join(django_face_file_path, face_file_name).replace("\\", "/")
	face.photo = photo
	face.save()


def new_tag(photo, tag, category='label', score=1, bounding_box=None):
	# TODO: Check if a tag with this text already exists
	# if it does, fail?

	# TODO: This function is probably not needed anymore

	if bounding_box is not None:
		x1 = bounding_box[0]
		y1 = bounding_box[1]
		x2 = bounding_box[2]
		y2 = bounding_box[3]
		new_tag = Tag.objects.create(tag=tag, score=score, photo=photo,
									startX=x1, startY=y1,
									endX=x2, endY=y2)
		if tag == 'person':
			new_face(photo, bounding_box, new_tag)

	else:

		# Now: If a tag with the same name already exists in this photo,
		# do not assign the new one
		# FIXME: Better way to do this?

		if len(Tag.objects.filter(photo=photo, tag=tag)) == 0:
			new_tag = Tag.objects.create(tag=tag, score=score, photo=photo, category=category)
			InvertedIndex.objects.create(tag=new_tag, photo=photo)
			return new_tag


def remove_tag(photo, tag_id):
	# Tag.objects.filter(photo=photo, tag=tag).delete()
	Tag.objects.get(pk=tag_id).delete()


def remove_photo(photo_id):
	Photo.objects.get(pk=photo_id).delete()


def add_tags(photo):

	path = os.path.join(BASE_DIR, 'public', os.path.normpath(photo.image.url)[1:])

	tags = MyWatsonApp.tag_image(path)

	print()

	for tag in tags:
		"""
		Only the description t[0] and score t[1]
		are needed for now
		"""

		# tag = Tag.objects.create(tag=t[0], score=t[1], photo=photo)
		# new_tag(photo, t[0], t[1])

		# TODO: remove repeated tags
		# TODO: differentiate type of tag? (landmark, text, color)???
		print(tag)
		description = (tag['description'][:TAG_MAX_SIZE] + '...') \
		 				if len(tag['description']) > TAG_MAX_SIZE \
						else tag['description']

		box = tag['box'] if 'box' in tag else None
		new_tag(photo, description, score=tag['score'], bounding_box=box)


def add_batch_tags(photos, user):

    paths = []
    for photo in photos:

        path = os.path.join(BASE_DIR, 'public', os.path.normpath(photo.image.url)[1:])
        path = urllib.parse.unquote(path)
        if os.stat(path).st_size <= IMG_MAX_SIZE_BYTES:
            paths.append(path)
        else:
            print("[TAGGING] ERROR: File is too big! Discarding...")
            print("(" + path + ")\n")
    if len(paths) <= 0:
        print("[TAGGING] No image was tagged.")
        return

    all_tags = MyWatsonApp.batch_tag(paths, user)
    tags_to_create = []
    descriptions = {}

    for i in range(len(photos)):
        photo = photos[i]
        tags = all_tags[i]
        for tag in tags:
            print(tag)
            description = (tag['description'][:TAG_MAX_SIZE] + '...') \
			 				if len(tag['description']) > TAG_MAX_SIZE \
							else tag['description']

            box = tag['box'] if 'box' in tag else None
            if box is None:
                box = [None] * 4
            x1 = box[0]
            y1 = box[1]
            x2 = box[2]
            y2 = box[3]

            category = tag['category']
            score = tag['score']
            new_tag = Tag(tag=description, category=category, score=score,
							startX=x1, startY=y1,
							endX=x2, endY=y2,
							photo=photo)

            if photo not in descriptions:
                descriptions[photo] = []

			# If a photo already has a tag, do not add the same
			# unless it is a person with a bounding box
            if description not in descriptions[photo] or \
						(description == 'person' and x1 is not None):

                descriptions[photo].append(description)
                tags_to_create.append(new_tag)

			# new_tag(photo, description, score=tag['score'], bounding_box=box)
    Tag.objects.bulk_create(tags_to_create)

    for tag in tags_to_create:
        if tag.tag == 'person' and tag.startX is not None:

			# Prevent duplicate tags containing the same face
			# This is only needed due to the bulk_create() call
            Tag.objects.get(
				photo=tag.photo,
				tag=tag.tag,
				startX=tag.startX,
				startY=tag.startY,
				endX=tag.endX,
				endY=tag.endY).delete()
            tag.save()
            box = [tag.startX, tag.startY, tag.endX, tag.endY]
            print("[MYWATSON] Extracting person face from", tag.photo)
            new_face(tag.photo, box, tag)


def crop(image_path, bounding_box, saved_location, resized_resolution=None):
	"""
	@param image_path: The path to the image to edit
	@param bounding_box: A tuple of x/y coordinates (x1, y1, x2, y2)
	@param saved_location: Path to save the cropped image
	"""

	image_obj = Image.open(image_path)

	# Ratio between the canvas on the browser and the original image
	if resized_resolution is not None:
		Rx = image_obj.width / resized_resolution[0]
		Ry = image_obj.height / resized_resolution[1]

		"""
		This method resizes the bounding box to the original ratio
		"""
		coords = (round(Rx * bounding_box[0]), round(Ry * bounding_box[1]),
				round(Rx * bounding_box[2]), round(Ry * bounding_box[3]))
	else:
		coords = bounding_box

	"""
	This method crops the resized image
	"""
	# coords = bounding_box
	# resized_image = image_obj.resize(resized_resolution, Image.ANTIALIAS)
	# cropped_img = resized_image.crop(coords)

	cropped_img = image_obj.crop(coords)
	cropped_img.save(saved_location)
	return coords


def get_next_number_file(folder, name):
	same_name_files = []
	for f in os.listdir(folder):
		if f.startswith(name.lower()):
			same_name_files.append(f)

	"""
	Gets the next number to append to the path
	e.g. if the last file was 'sun_3.jpg', this file will be 'sun_4.jpg'
	"""

	number = int(same_name_files[-1].split('.')[0].split('_')[-1]) + 1
	return number


def add_new_tag(photo, tag, bounding_box, resized_resolution):

	#############################################
	# In case of a person...
	#############################################
	is_person = False

	if ":" in tag:
		tokens = tag.split(":")
		if tokens[0] == "person":
			is_person = True
			tag = tokens[-1].strip()
			folder = FACE_IMAGES_FOLDER

	else:
		folder = CROPPED_IMAGES_FOLDER
	save_location = os.path.join(folder, tag.lower() + '_0.jpg')



	if os.path.exists(save_location):
		# number = get_next_number_file(folder, name)
		"""
		Gets the images that correspond to the same tag
		"""
		same_name_files = []
		for f in os.listdir(folder):
			if f.startswith(tag.lower()):
				same_name_files.append(f)

		"""
		Gets the next number to append to the path
		e.g. if the last file was 'sun_3.jpg', this file will be 'sun_4.jpg'
		"""

		number = int(same_name_files[-1].split('.')[0].split('_')[-1]) + 1
		save_location = os.path.join(folder, tag.lower()+'_'+str(number)+'.jpg')

	coords = crop(photo.image, bounding_box, save_location, resized_resolution=resized_resolution)
	new_tag(photo, tag, bounding_box=coords)

	if is_person:
		Face.objects.create(face=save_location, photo=photo)

	return

###############################################################################


class GalleryView(generic.ListView):
	template_name = 'mywatson/index.html'
	context_object_name = 'photos'

	def get_queryset(self):

mywatson_site/mywatson/templates/mywatson/add_tag.html
{% extends 'mywatson/base.html' %}
{% load static %}

{% block title %}Photo {{ photo.id }} - New tag{% endblock %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'mywatson/base.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'mywatson/photo_details.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'mywatson/add_tag.css' %}" />

<div class="content-wrapper">

  <div class="img-wrapper">

    <!--<img class="img-img" src="{{ photo.image.url }}">-->
    <div class="img-img">
      <canvas id="img_canvas"></canvas>
    </div>

    <script>
        var imgurl = '{{ photo.image.url }}'
        var photo_id = '{{ photo.id }}'
    </script>
    <script src="{% static 'mywatson/draw_box.js' %}"></script>

    <div class="img-nav">
      <a href="{% url 'mywatson:photo' photo.id %}" class="img-nav-control img-previous">
        <span class="glyphicon glyphicon-chevron-left"></span>
        Back to photo
      </a>
    </div>
  </div>


</div>


{% endblock %}

mywatson_site/mywatson/templates/mywatson/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">
    <!-- Themify Icons -->
    <link rel="stylesheet" href="{% static 'core/css/themify-icons.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'core/navbar.css' %}" />

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'core/images/mywatson_logo.png' %}"/>
    <link rel="icon" type="image/x-icon" href="{% static 'core/images/mywatson_logo.png' %}"/>


    <script src="{% static 'core/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'core/js/bootstrap.bundle.min.js' %}"></script>


    <link rel="dns-prefetch" href="//fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500" rel="stylesheet">


  <title>{% block title %}MyWatson{% endblock %}</title>

</head>

<!--<body id="bg" style="background-image: url('{% static "core/images/ai-bg.jpg"%}')">-->
<body id="bg">

    <div class="nav-menu fixed-top">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <nav class="navbar navbar-dark navbar-expand-lg">
                        <a class="navbar-brand" href="{% url 'landing' %}">
							<!-- My<span style="font-weight: 500;">Watson</span> -->
							<img src="{% static 'core/images/mywatson_transparent.png' %}" class="img-fluid" alt="logo">
						</a> <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>
                        <div class="collapse navbar-collapse" id="navbar">
                            <ul class="navbar-nav ml-auto">
                                <li class="nav-item"> <a id="gallery" class="nav-link active" href="{% url 'mywatson:index' %}">GALLERY</a> </li>
                                <li class="nav-item"> <a id="upload" class="nav-link" href="{% url 'mywatson:upload_photo' %}">UPLOAD PHOTO</a> </li>
                                <li class="nav-item"> <a id="people" class="nav-link" href="{% url 'mywatson:get_people' %}">PEOPLE</a> </li>
                                <form id="search-bar" class="navbar-form navbar-left" action="{% url 'mywatson:query' %}" method="get">
                                  <div class="input-group">
                                    <input type="text" class="form-control" name="q" placeholder="Search">
                                    <div class="input-group-btn">
                                      <button class="btn btn-default" type="submit">
                                        <i class="ti-search"></i>
                                      </button>
                                    </div>
                                  </div>
                                </form>


                            </ul>
                            <ul class="navbar-nav ml-auto navbar-right">
                                <li id="greetings-user" class="nav-item"><span class="ti-user"></span><span id="username-label">{{ user.get_username }}</span></li>
                                <li class="nav-item"><a href="{% url 'logout' %}" class="btn btn-outline-light my-3 my-sm-0 ml-lg-3">Logout</a></li>

                            </ul>


                        </div>
                    </nav>

                </div>
            </div>
        </div>

        <script>


            $(".navbar-nav").find("#gallery").removeClass("active");
            var url = window.location.pathname;
            tokens = url.split('/')
            if (tokens.includes("upload")) {
            $   (".navbar-nav").find("#upload").addClass("active");
            }
            else if (tokens.includes("people") || tokens.includes("get_people")) {
                $(".navbar-nav").find("#people").addClass("active");
            }
            else {
                $(".navbar-nav").find("#gallery").addClass("active");
            }

        </script>
    </div>

  <div id="content">
	  <div id="wait-modal">
	  </div>

	  {% block content %} {% endblock %}

  </div>

</body>

</html>

mywatson_site/mywatson/templates/mywatson/base_bak0.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <link rel="stylesheet" type="text/css" href="{% static 'core/background.css' %}" />

  <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}"/>
  <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}"/>



  <title>{% block title %}MyWatson{% endblock %}</title>

</head>

<!--<body id="bg" style="background-image: url('{% static "core/images/ai-bg.jpg"%}')">-->
<body id="bg">

  <div id="navbar">
    {% block navbar %}
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a href="{% url 'mywatson:index' %}" class="navbar-brand" href="#">MyWatson</a>
        </div>
        <ul class="nav navbar-nav">
          <li id="gallery" class="active"><a href="{% url 'mywatson:index' %}">Gallery</a></li>
          <li id="upload"><a href="{% url 'mywatson:upload_photo' %}">Upload photos</a></li>
          <li id="people"><a href="{% url 'mywatson:get_people' %}">People</a></li>
        </ul>

        <form class="navbar-form navbar-left" action="{% url 'mywatson:query' %}" method="get">
          <div class="input-group">
            <input type="text" class="form-control" name="q" placeholder="Search">
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit">
                <i class="glyphicon glyphicon-search"></i>
              </button>
            </div>
          </div>
        </form>

        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <p class="navbar-text">Hello, {{ user }}!</p>
            <li><a href="{% url 'logout' %}">Log out</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <script>


        $(".nav").find("#gallery").removeClass("active");
        var url = window.location.pathname;
        tokens = url.split('/')
        if (tokens.includes("upload")) {
        $   (".nav").find("#upload").addClass("active");
        }
        else if (tokens.includes("people")) {
            $(".nav").find("#people").addClass("active");
        }
        else {
            $(".nav").find("#gallery").addClass("active");
        }

    </script>
    {% endblock %}
  </div>

  <div id="content">
	  <div id="wait-modal">
	  </div>

	  {% block content %} {% endblock %}
  </div>

</body>

</html>

mywatson_site/mywatson/templates/mywatson/photo_details_safe.html
{% extends 'mywatson/base.html' %}
{% load static %}

{% block title %}Photo {{ photo.id }}{% endblock %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'mywatson/base.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'mywatson/photo_details.css' %}" />


<div class="content-wrapper">
    <div class="tags-wrapper">

      <div class="tags-header">Tags</div>
      <div class="list-group">
        {% for tag in view.tags %}
          <div class="list-group-item" id='{{ tag.id }}'>
            <span>{{ tag.tag }}</span>
            <form id="removetags" action="{% url 'mywatson:photo' photo.id%}" method="post">
              {% csrf_token %}
              <input name="remove_tag" type="submit" class="btn-remove-tag" value="_" />
              <input type='hidden' value='{{ tag.id }}' name='tag'>
            </form>


          </div>
        {% endfor %}
      </div>


      <a href="{% url 'mywatson:add_tag' photo.id %}" class="img-nav-control tag-add">
        <span class="glyphicon glyphicon-plus"></span>
        Add tags
      </a>

      <form id="remove_photo" action="{% url 'mywatson:photo' photo.id%}" method="post">
        {% csrf_token %}
        <input name="remove_photo" type="submit" id="remove-btn" class="img-nav-control img-remove" value="Remove photo" />
        <input type='hidden' value='{{ photo.id }}' name='photo' />
      </form>

    </div>

    <div class="img-wrapper">
      <img class="img-img" src="{{ photo.image.url }}">
      <div class="img-nav">

        <a href="{% url 'mywatson:photo' view.previous_photo.id %}" class="img-nav-control img-previous">
          <span class="glyphicon glyphicon-chevron-left"></span>
          Previous
        </a>

        <a href="{% url 'mywatson:photo' view.next_photo.id %}" class="img-nav-control img-next">
          Next
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>

      </div>
    </div>

</div>


{% endblock %}